server:
  port: 8000

spring:
  datasource:
    #initialization-mode: always
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: root
    schema: classpath:script/schema.sql
    data: classpath:script/data.sql
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    
feign:
  client:
    config:
      feignName:
        connectTimeout: 160000000
        readTimeout: 160000000