server:
  port: 8009
   
   
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    defaultEncoding: UTF-8 # Default message encoding
    username: samyuktatech@gmail.com
    password: sandy@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
    
# Email subjects    
subject:
  user-verification-code: Verification Code
from: info@abc.com
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
 