server:
  port: 8080 
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url:  jdbc:mysql://localhost:3306/sample
    username: root
    password: root
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
    
