spring:
  application:
    name: auth-server    
  jpa:
    hibernate:
      ddlAuto: update    
  datasource:
    initialization-mode: ALWAYS
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    schema: classpath:script/schema.sql
    data: classpath:script/data.sql