spring:
  application:
    name: auth-server    
  jpa:
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       
  datasource:
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    schema: classpath:script/schema.sql
    data: classpath:script/data.sql